version: '3.5'
services:
  ide: 
    build:
      context: ./docker
      dockerfile: ide.Dockerfile
    command: ["--allow-http", "--no-auth"]
    volumes:
      - type: bind
        source: .
        target: /home/coder/project
    ports:
      - "8443:8443"
  webserver:
    build:
      context: ./docker
      dockerfile: webserver.Dockerfile
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
    ports:
      - "80:80"
      - "9000:9000"
  database:
    image: mysql:8.0.17
    command: ["--default-authentication-plugin=mysql_native_password"]
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    environment:
      PMA_HOST: "database"
      PMA_USER: "root"
      PMA_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "8080:80"

volumes:
  db-data: